### ISSUE TITLE
Rename to core?

### ISSUE THREAD

**Issue by Sorixelle** [auxolotl/core#5]
As far as I've seen, most people have been calling this the `core` repo (myself included) - do we want to rename the repo to reflect this?

**Comment by isabelroses** [comment]
I have renamed the repo to core. Leaving the issue open for now to allow devs and users alike to readjust and fix any issues this might have caused.

**Comment by Sorixelle** [comment]
I think we've got everywhere covered - feel free to reopen if something was missed.
