### ISSUE TITLE
Package request: Lix

### ISSUE THREAD

**Issue by aprilthepink** [auxolotl/core#6]
I think we should even go ahead and set it as the default Nix package in the repo!
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sorixelle** [comment]
I think this is better suited for adding to Core - nixpkgs does not have a great way to import Nix sources from an external location, and I would rather not duplicate Lix's expressions into our repos. Does mean we don't have a great way to use it at the moment, but packaging Lix should definitely be a goal.

**Comment by isabelroses** [comment]
> I think this is better suited for adding to Core

Probably yes.

> I would rather not duplicate Lix's expressions into our repos

Honestly, I think it is fine at this stage.

**Comment by aprilthepink** [comment]
> > I think this is better suited for adding to Core
> 
> Probably yes.
> 
> > I would rather not duplicate Lix's expressions into our repos
> 
> Honestly, I think it is fine at this stage.

we can take this as a opportunity to make auxolotl use flakes more. Nixpkgs approach was a "all in one repo", but here we could maybe link to to modules in different repos like Lix to integrate that.

Depends on whenever or not we are ready to move on from the pre-flake state of nix.

**Comment by Sorixelle** [comment]
I don't think there's anything stopping us from doing that in Core, we're already playing with primarily flake-based structures there. It should be doable.

**Comment by isabelroses** [comment]
I currently believe the end goal of aux is to provide packages that are not in a mono repo so I think I agree with @Sorixelle and shall transfer this over to the core repo.

**Comment by isabelroses** [comment]
lix was packaged as of https://github.com/auxolotl/core/pull/2, you can find it here https://github.com/auxolotl/core/blob/main/pkgs/by-name/li/lix/packages.nix
